version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

  frontend:
    build:
      context: ./frontend
    container_name: vue-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules 
    command: npm run dev
    environment:
      - NODE_ENV=development

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}  # Valor por defecto
      MYSQL_DATABASE: ${MYSQL_DATABASE:-weather_chatbot}
      MYSQL_USER: ${MYSQL_USER:-chatbot_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_ROOT_HOST: '%'
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --skip-name-resolve
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql 
    ports:
      - "3307:3306"

volumes:
  mysql_data:
